"""Public bilingual records. Internal schedules and HOLD materials are excluded."""
def bi(zh, en):
    return {"zh": zh, "en": en}

def record(id, year, kind, status, zh, en, org_zh, org_en, meta_zh, meta_en, desc_zh, desc_en):
    return dict(id=id, year=year, kind=kind, status=status, title=bi(zh,en), org=bi(org_zh,org_en), meta=bi(meta_zh,meta_en), description=bi(desc_zh,desc_en))

RECORDS = [
record('A1',2026,'talk','past','AI 時代的職場素養：人機協作實戰必修課','Workplace Literacy in the AI Era: Human–AI Collaboration','觀音產業園區','Guanyin Industrial Park','製造業主管｜3 小時｜實體','Manufacturing managers · 3 hours · In person','從 AI 使用風險與資料判斷出發，練習用 AI 前的四個問題、資料改寫與跨部門情境。由經濟部觀音產業園區服務中心、元智大學研發處主辦，元智大學企業書院協辦。','A session for manufacturing managers on AI risks, data handling and cross-functional scenarios. Organised by the Guanyin Industrial Park Service Center and Yuan Ze University’s research and development office, with support from the university’s enterprise college.'),
record('A2',2026,'talk','past','用 AI 與數位化打造「省時又安全」的作業管理','Using AI and Digital Tools for Safer, More Efficient Operations','觀音產業園區','Guanyin Industrial Park','廠長、環安衛與現場管理幹部｜3 小時','Plant, EHS and operations managers · 3 hours','從簡化紙本與現場流程切入，討論 AI 如何輔助作業管理，兼顧資訊安全與工安。與上午場由相同單位主辦、協辦，於觀音產業園區服務中心完成授課。','An operations-focused session on reducing paperwork and simplifying workflows while considering both cybersecurity and workplace safety. Delivered at the Guanyin Industrial Park Service Center as the afternoon session of the same programme.'),
record('A3',2026,'talk','past','校務資安與風險防治：AI 時代版','Campus Cybersecurity and Risk Management in the AI Era','元智大學教務處','Office of Academic Affairs, Yuan Ze University','臺北市八所高中校長｜2 小時','Principals from eight Taipei high schools · 2 hours','由元智大學教務處主辦，從校長的管理責任與決策出發，結合校園案例、學生資料保護、AI 使用風險與分階段行動清單。','Organised by Yuan Ze University’s Office of Academic Affairs for principals from eight Taipei high schools. Covers management decisions, campus scenarios, student data protection, AI risks and phased action planning.'),
record('A4',2026,'talk','past','駭客攻防戰：AI 代理與人類誰能勝出？','AI Agents and Humans in Cyber Offence and Defence','台灣中小企業資訊安全協會','台灣中小企業資訊安全協會 (TWSMEISA)','科學園區同業公會｜研討會短講・15 分鐘','Science park industry association venue · 15-minute talk','於協會主辦的資安研討會，從 AI 代理攻擊、防禦自動化與人的判斷切入，討論企業應如何掌握自主化的界線。','A conference talk on AI-assisted attacks, defensive automation and decisions that require human judgement, delivered at a security seminar organised by TWSMEISA.'),
record('A6',2026,'workshop','design','AI 工作流需求分析與系列工作坊設計','AI Workflow Needs Analysis and Workshop Design','自雇者與微型工作者','Self-employed professionals and micro-businesses','需求分析與課程設計','Needs analysis and curriculum design','根據 147 份學員需求資料，規劃帳務、個案管理、個人網站、知識管理、內容與課程製作等六個工作坊主題，以實作與可持續使用的工作流程為核心。','A curriculum designed from 147 learner needs records, covering bookkeeping, client management, personal websites, knowledge management, content and course creation. The focus is practical workflows that learners can continue using.'),
record('A7',2026,'talk','scheduled','如何安全的使用AI工具及應用實務？','Using AI Tools Safely: Practical Applications','亞旭','Askey','資安委員會例會｜預定 2 小時','Cybersecurity committee meeting · Planned duration: 2 hours','面向企業內部資安委員會的 AI 工具安全使用演講。','An invited talk on safe use of AI tools for a corporate cybersecurity committee meeting.'),
record('A8',2026,'talk','past','AI 工具安全使用','Safe Use of AI Tools','咖米股份有限公司','Kamee Inc.','企業內部演講','Internal corporate talk','2026 年面向咖米同仁的企業內部演講，聚焦 AI 工具日常應用中的資料保護與安全判斷。','A 2026 internal talk for Kamee employees, focused on data protection and security decisions in everyday use of AI tools.'),
record('A9',2025,'talk','past','AI 世代下的簡單型零信任','Practical Zero Trust in the AI Era','彰化縣工業會','Changhua County Industrial Association (CHCIA)','企業負責人及資安主管｜20 分鐘','Business owners and security managers · 20 minutes','於「中小企業資安實務（資安很簡單）」活動演講。活動由彰化縣工業會主辦，資策會資安科技研究所、台灣中小企業資訊安全協會及長茂科技協辦。','A talk in the SME cybersecurity programme hosted by CHCIA, with supporting organisations including 資策會資安科技研究所, TWSMEISA and EverMore Tech. The session addressed business owners and managers responsible for cybersecurity.'),
record('A10',2024,'talk','past','AI資安與零信任研討會','AI Cybersecurity and Zero Trust Seminar','中華電信學院','中華電信學院','研討會演講','Seminar speaking engagement','於中華電信學院參與 AI 資安與零信任主題研討會演講。','A speaking engagement on AI cybersecurity and zero trust at 中華電信學院.'),
record('B1',2026,'course','course','從 LLM 威脅建模到風險控管與治理（實作）','LLM Threat Modelling, Risk Management and Governance','自強基金會','Tze-Chiang Foundation of Science & Technology','2 次・共 12 小時｜實作課程','2 sessions · 12 hours · Hands-on course','從保護 LLM 系統到以 LLM 輔助資安工作，結合理論與 10 項實作。教材採本地模型及離線環境設計，將風險辨識連到控制措施與治理討論。','Theory and ten labs connect LLM threat modelling with controls and governance. The course addresses both securing LLM systems and applying LLMs to security work, using local models and offline lab environments.'),
record('B2',2026,'course','scheduled','AI 資安應用實務：事中應變','AI for Cybersecurity: Incident Response','中華軟體公會','中華軟體公會','3 小時｜2 本 Colab 實作教材','3 hours · 2 Colab lab notebooks','結合 AI 輔助研判與人工決策，以合成資料練習事中應變，不要求 Python 基礎。實體授課場地為 iSpan 資展國際台北分公司。','AI-assisted analysis and human decision-making using synthetic incident data. Two Colab notebooks support learners without a Python background. The in-person venue is iSpan’s Taipei branch.'),
record('B3',2026,'course','preparation','AI × 資安線上課程三部曲','AI and Cybersecurity: Online Course Series','線上課程規劃','Online course development','治理、智能化維運、攻防誘捕','Governance, intelligent operations, offence and deception','規劃以治理、智能化安全營運與攻防誘捕為主軸的線上課程，內容仍在籌備。','An online series in preparation, covering governance, AI-assisted security operations, and offensive and deception techniques.'),
record('B4',2026,'teaching','teaching','資料結構教材改版','Data Structures Courseware','元智大學資訊工程學系','Department of Computer Science and Engineering, Yuan Ze University','大學課程教材','University courseware','重新整理資料結構講義的章節與學習路徑，讓概念、範例與練習相互銜接。','Reorganised data structures lecture notes to connect concepts, examples and exercises in a clear learning sequence.'),
record('B6',2026,'course','course','AI 賦能安全營運中心（SOC）智能化應用實務（實作）','AI-Enabled Security Operations Centre: Practical Applications','自強基金會','Tze-Chiang Foundation of Science & Technology','2 次・共 12 小時','2 sessions · 12 hours','以 AI 在安全營運中心的應用為課程主題，面向希望理解 SOC 智能化的技術團隊。','A course on applying AI in security operations centres, for technical teams exploring AI-assisted SOC workflows.'),
record('B7',2026,'course','scheduled','駭客滲透攻擊與 Honeypot 誘捕防禦攻防實務（實作）','Penetration Attacks and Honeypot Deception Defence','自強基金會','Tze-Chiang Foundation of Science & Technology','2 次・共 12 小時','2 sessions · 12 hours','以滲透攻擊及 Honeypot 誘捕防禦為主題的實作課程，已排定開課。','A scheduled hands-on course on penetration attacks and honeypot-based deception defence.'),
record('B8',2024,'course','past','資安威脅與AI偵測應用','Cybersecurity Threats and AI Detection Applications','自強基金會','Tze-Chiang Foundation of Science & Technology','歷年授課紀錄','Past course','2024 年於自強基金會開設的資安威脅與 AI 偵測主題課程。','A 2024 course at TCFST on cybersecurity threats and AI-based detection.'),
record('B9',2025,'course','past','主動式資安防禦實務','Practical Proactive Cyber Defence','自強基金會','Tze-Chiang Foundation of Science & Technology','同一門課・兩次授課','One course · Two sessions','2025 年開設，課程分 Day 1、Day 2 兩次授課，主題為主動式資安防禦實務。','A 2025 course on proactive cyber defence, delivered across Day 1 and Day 2.'),
record('B10',2025,'course','past','零信任的實現與挑戰','Implementing Zero Trust: Challenges and Practice','自強基金會','Tze-Chiang Foundation of Science & Technology','歷年授課紀錄','Past course','2025 年於自強基金會開設，以零信任的實現與挑戰為主題。','A 2025 TCFST course on zero-trust implementation and its challenges.'),
record('B11',2025,'course','past','智慧資安化 & 資安智慧化','Securing AI and Applying AI to Security','自強基金會','Tze-Chiang Foundation of Science & Technology','歷年授課紀錄','Past course','2025 年於自強基金會開設，從智慧系統的安全及資安工作的智能化兩個方向探討 AI 與資安。','A 2025 TCFST course addressing security for intelligent systems and the use of AI in cybersecurity.'),
record('B12',2025,'series','past','AI 資安學院系列課程','AI Cybersecurity Academy Course Series','資安署','Administration for Cyber Security, moda','FY114｜系列課程授課紀錄','FY114 (2025) · Series teaching record','參與資安署 AI 資安學院系列課程授課。','Teaching participation in the Administration for Cyber Security’s AI Cybersecurity Academy course series.'),
record('B13',2024,'collaboration','record','AI結合資安情資研析合作案','AI-Assisted Cyber Threat Intelligence Analysis Collaboration','資安署','Administration for Cyber Security, moda','FY113｜授課相關合作紀錄','FY113 (2024) · Teaching-related collaboration','資安署 AI 結合資安情資研析合作案之授課相關紀錄。','A teaching-related collaboration associated with AI-assisted cyber threat intelligence analysis for the Administration for Cyber Security.'),
record('B14',2024,'course','past','人工智慧及資安鑑識課程','Artificial Intelligence and Cybersecurity Forensics','資安署','Administration for Cyber Security, moda','FY113｜歷年授課紀錄','FY113 (2024) · Past course','資安署人工智慧及資安鑑識主題課程授課。','Teaching on artificial intelligence and cybersecurity forensics for the Administration for Cyber Security.'),
]

STATUS = {
'past':bi('過往紀錄','Past engagement'), 'scheduled':bi('已排定','Scheduled'),
'course':bi('課程介紹','Course overview'), 'design':bi('課程設計','Curriculum design'),
'preparation':bi('籌備中','In preparation'), 'teaching':bi('教材開發','Courseware'),
'record':bi('合作紀錄','Collaboration'), 'topic':bi('演講主題','Talk topic')}
